### ISSUE TITLE
"Change Package" doesn't work due to API change.

### ISSUE THREAD

**Issue by LeCodeCo** [TrixterTheTux/Pterodactyl-WHMCS#10]
https://file.properties/paste/qatajusezu is the error that appears when you try and change package. A field to choose the database limit would also be nice. 😄

**Comment by TrixterTheTux** [comment]
Sorry for the delay, fixed in https://github.com/TrixterTheTux/Pterodactyl-WHMCS/commit/4c9d02ecc166df0bf5e885d7498c5bd634d84eba
