### ISSUE TITLE
Resolving timed out after 5000 milliseconds

### ISSUE THREAD

**Issue by ssdrive-flaktra** [TrixterTheTux/Pterodactyl-WHMCS#113]
hello, I have an error in the WHMCS logs.
the server (using ssh) can resolve the panel just fine, but whmcs can't
the error is Resolving timed out after 5000 milliseconds
can anyone help?

**Comment by TrixterTheTux** [comment]
Please use the [Pterodactyl Discord](https://discord.gg/pterodactyl) (#whmcs-module channel) for configuration related support instead of GitHub issues.

**Comment by ssdrive-flaktra** [comment]
But no one helps there, it's a dead chat. If you always tell them to go to the pterodactyl discord, just lock issues and put a pinned issue saying go to the discord.
