### ISSUE TITLE
WHMCS Addon - Deploys Game Server To Previous (Few Orders Back) Client.

### ISSUE THREAD

**Issue by laneromano** [TrixterTheTux/Pterodactyl-WHMCS#115]
Hello,

What is occurring is when I accept orders with this addon, it sets the email of that game server to a random / earlier orders client email. So say test@test.net purchased a server yesterday and I get an order today, instead of john@john.com receiving the game server it goes to the user test@test.net and I have to manually change it to the client.

Please help assist,
Thanks
~Lane

**Comment by TrixterTheTux** [comment]
Please use the [Pterodactyl Discord](https://discord.gg/pterodactyl) (#whmcs-module channel) for configuration related support instead of GitHub issues.
