### ISSUE TITLE
Display Username And Password For Login On Panel

### ISSUE THREAD

**Issue by JS-B-OT** [TrixterTheTux/Pterodactyl-WHMCS#117]
How to display username and password so that buyer can log in to the panel
![Screenshot (15)](https://user-images.githubusercontent.com/74894397/161416776-cbbdbc59-9175-4867-b8a8-3c6fa2b1e8e2.png)

**Comment by trenutoo** [comment]
Refer to the FAQ that covers [this. ](https://github.com/pterodactyl/whmcs#the-usernamepassword-field-is-empty-how-does-the-user-get-credentials)

WHMCS itself doesn't know the credentials.
