### ISSUE TITLE
Database amount in module settings

### ISSUE THREAD

**Issue by OptNode** [TrixterTheTux/Pterodactyl-WHMCS#12]
Please can we specify the amount of databases a user can use in the module settings please. This would be a great new addition to ur module!

**Comment by mayed505** [comment]
That's already been added :)

**Comment by TrixterTheTux** [comment]
Not in the module settings, only the ability to overwrite them.

**Comment by OptNode** [comment]
Yep, reason why I’m requesting this to be added. Would be really good to specify an amount for higher packages and purchasing extras as an add on.

**Comment by TrixterTheTux** [comment]
Forgot to close this, was added in https://github.com/TrixterTheTux/Pterodactyl-WHMCS/commit/fca59fa7b6b63175ec00047250e278d27b4479a7
