### ISSUE TITLE
Link existing server to product whmcs

### ISSUE THREAD

**Issue by anondev-sudo** [TrixterTheTux/Pterodactyl-WHMCS#122]
Could you please add way to link a existing server (on pterodactyl) to product on whmcs? Server link button should be there here displayed in client area and when invoice is unpaid, server should be suspended, etc.

Useful when user already has server on panel and you want to bill the user for it using whmcs.

**Comment by TrixterTheTux** [comment]
Setting the server's `external_id` to the service's ID will already do this.

**Comment by anondev-sudo** [comment]
Will be the button displayed there too?

**Comment by anondev-sudo** [comment]
Also you just can't make order from admin area and make that new server won't be deployed on ptero but existing server will be used instead
