### ISSUE TITLE
Errors with new APIs

### ISSUE THREAD

**Issue by Moi045** [TrixterTheTux/Pterodactyl-WHMCS#124]
Since the last updates with the Pterodactyl API changes, the WHMCS module has started to fail as the panel returns the API request with 404. I will leave images below this text for better understanding

![Captura](https://user-images.githubusercontent.com/79182615/172962215-1cc87e0f-e330-412b-90fb-739c6d77aa8a.PNG)

![Captura2](https://user-images.githubusercontent.com/79182615/172962298-edaac2bb-064b-4051-b92b-176a0178dbc5.PNG)

![Captura3](https://user-images.githubusercontent.com/79182615/172962358-ec58bd56-25af-47f7-9bf4-934837ce4faa.PNG)

I don't know if there is any temporary solution until you update the module

**Comment by trenutoo** [comment]
There's no egg with such egg id inside the specified nest. It's not related to any panel updates.
