### ISSUE TITLE
Add start, stop, restart and reinstall buttons

### ISSUE THREAD

**Issue by anondev-sudo** [TrixterTheTux/Pterodactyl-WHMCS#126]
Add buttons to whmcs clientarea for starting, stopping, restarting and reinstalling the server. For example whmcs module for virtualizor has that too.

**Comment by TrixterTheTux** [comment]
This doesn't really make sense to do for game servers (they can't see server state or console, nor if it actually started), and expecting someone to open a game panel to manage their server doesn't sound unreasonable to me.
