### ISSUE TITLE
Module Create Failed - Service ID: 289 - Error: Failed to create the server, received the error code: 422. Enable module debug log for more info.

### ISSUE THREAD

**Issue by SwumoNotSwumo** [TrixterTheTux/Pterodactyl-WHMCS#127]
Hello, i have a error how can i fix it
![chhhh](https://user-images.githubusercontent.com/93037013/182046793-76c2a74d-894b-474f-8071-20d9e04cb783.png)
![chhhhhh](https://user-images.githubusercontent.com/93037013/182046794-be2c1c7c-b321-4208-9bea-2cad3c081431.png)
?

**Comment by TrixterTheTux** [comment]
Please use the [Pterodactyl Discord](https://discord.gg/pterodactyl) (#whmcs-module channel) for configuration related support instead of GitHub issues.

**Comment by SwumoNotSwumo** [comment]
> Please use the [Pterodactyl Discord](https://discord.gg/pterodactyl) (#whmcs-module channel) for configuration related support instead of GitHub issues.

Does not help!
