### ISSUE TITLE
i face this issue Invalid status_code received: 401. Possible solutions: Authorization header either missing or not provided.

### ISSUE THREAD

**Issue by robertgomes21** [TrixterTheTux/Pterodactyl-WHMCS#128]
i face this issue Invalid status_code received: 401. Possible solutions: Authorization header either missing or not provided.

https://imgur.com/a/emiL4FJ

**Comment by TrixterTheTux** [comment]
Please use the [Pterodactyl Discord](https://discord.gg/pterodactyl) (#whmcs-module channel) for configuration related support instead of GitHub issues.
