### ISSUE TITLE
Source Games

### ISSUE THREAD

**Issue by PaziHD** [TrixterTheTux/Pterodactyl-WHMCS#13]
How can we add custom fields to send with the module?
Source games aren't working for me because it requires STEAM_ACC and the module doesn't include that and I don't know how to add it.

Thanks.

**Comment by TrixterTheTux** [comment]
How to use the custom fields with the module can be found here: https://github.com/TrixterTheTux/Pterodactyl-WHMCS#overwriting-values-through-configurable-options

**Comment by PaziHD** [comment]
Ah yes, thank you. I'm utilizing this for a few features now.
