### ISSUE TITLE
Suggestion about cpu pinning

### ISSUE THREAD

**Issue by Rezanans-wow** [TrixterTheTux/Pterodactyl-WHMCS#132]
Hello everyone,

I want to suggest add support of feature 'Cpu pinning' at pterodactyl WHMCS module.
Pretty sure, not many users know how use it for get better resource allocation

But, this feature i think needed to be added in module, because sometimes its really needed (For limit usage at CPU cores)
As primary ideas, its limit №1 and №2 plans for example, 1-7 theard should use №1, 0,8-12 should use №2. Its just example, and can be used for other things.

**Comment by Jcodeerd** [comment]
Same cpu, same storage device, same ram. What makes it "premium" lmao?

**Comment by Jcodeerd** [comment]
Same cpu, same storage device, same ram. What makes it "premium" lmao?

**Comment by Rezanans-wow** [comment]
> Same cpu, same storage device, same ram. What makes it "premium" lmao?

I just maked example, i written eample two times for understand you its example. Its just wanted to convey exactly what can be done. (Allocate one rate 1-6 | 0.7-12)

**Comment by TrixterTheTux** [comment]
I'd really like to know what the intended use case here is because I feel like this will cause a lot of confusion than actual benefit, and as pointed out the provided example doesn't make any sense.

**Comment by Rezanans-wow** [comment]
> I'd really like to know what the intended use case here is because I feel like this will cause a lot of confusion than actual benefit, and as pointed out the provided example doesn't make any sense.

Ok, sorry
