### ISSUE TITLE
Use username from email instead random one

### ISSUE THREAD

**Issue by anondev-sudo** [TrixterTheTux/Pterodactyl-WHMCS#135]
How can I make your whmcs mobile use username from email address and not generate random character username when making account on pterodactyl.

**Comment by TrixterTheTux** [comment]
As mentioned over Discord (multiple times), you'd need to modify the module to do your desired behavior. The username is random for a reason to avoid conflicts which would otherwise prevent the user from being created => deployment failing.

**Comment by anondev-sudo** [comment]
You can keep it open to see if people like it

**Comment by anondev-sudo** [comment]
If username from email fails random username can be used

**Comment by anondev-sudo** [comment]
If user doesn't have set last name on whmcs, user create fails too. Whmcs can be set to have last name optional. The module shouldn't send empty (null value) last_name to pterodactyl api when last name isn't set on whmcs
