### ISSUE TITLE
error on whmcs

### ISSUE THREAD

**Issue by ghost** [TrixterTheTux/Pterodactyl-WHMCS#136]
TypeError: call_user_func(): Argument #1 ($callback) must be a valid callback, function "pterodactyl_config" not found or invalid function name in /home/admin/domains/foxxnode.com/public_html/admin/configaddonmods.php:0
Stack trace:
#0 {main}

**Comment by TrixterTheTux** [comment]
You’ll need to provide a lot more of context, what you’re trying to do, when does the error happen, how to reproduce this error, etc,

**Comment by ghost** [comment]
i go to the addon page
i get this error

**Comment by ghost** [comment]
so
i cant activate it..

**Comment by yesBad** [comment]
![Screenshot_20230622_114258_Chrome.png](https://github.com/pterodactyl/whmcs/assets/87938689/965430ff-f452-40b4-a397-134186b67111)

🤔
