### ISSUE TITLE
Error 0

### ISSUE THREAD

**Issue by vMax-dev1** [TrixterTheTux/Pterodactyl-WHMCS#138]
Hello i have this error

**Invalid status_code received: 0. Possible solutions: Check module debug log for more detailed error.**

![image](https://github.com/pterodactyl/whmcs/assets/4140252/5cd8fd2f-9090-4593-991c-a235761eda01)

**Comment by TrixterTheTux** [comment]
Please use the [Pterodactyl Discord](https://discord.gg/pterodactyl) (#whmcs-module channel) for configuration related support instead of GitHub issues.
