### ISSUE TITLE
The Port format is invalid.

### ISSUE THREAD

**Issue by droxydevelopement** [TrixterTheTux/Pterodactyl-WHMCS#143]
This is the only problem i'm facing

**Comment by karfakias** [comment]
did you found a fix?

**Comment by BGDrew** [comment]
yes i have this issue to 
![image1](https://github.com/pterodactyl/whmcs/assets/162998762/89f61393-0ca9-45f8-9e6e-649a37c48f54)

**Comment by BGDrew** [comment]
yes its the only problem

**Comment by TheTrueColonel** [comment]
Remove "https://" from your host name.
