### ISSUE TITLE
The Port format is invalid

### ISSUE THREAD

**Issue by BGDrew** [TrixterTheTux/Pterodactyl-WHMCS#147]
when trying to add Pterodactyl WHMCS module it is coming up with The port Format is Invalid can anyone help me with what i need to do.

Thanks 
![image1](https://github.com/pterodactyl/whmcs/assets/162998762/dd0bdd97-dc57-48d7-8489-fe759a2edb92)

**Comment by TheTrueColonel** [comment]
Remove "https://" from your host name.
