### ISSUE TITLE
Invalid status_code received: 301. Possible solutions: None.

### ISSUE THREAD

**Issue by Skryptio** [TrixterTheTux/Pterodactyl-WHMCS#148]
I've tried adding "https://" to the hostname, I've tried removing it and I've even tried "http://". It all doesn't work. I use Cpanel for WHMCS. Each time I click test connection I get the error stated in the title, I've tried moving the hash from password field to "Access Hash" field which also doesn't make any difference. Error code 301 means a redirect is happening but I don't know how to avoid a redirect from happening.
![afbeelding_2024-05-10_021105564](https://github.com/pterodactyl/whmcs/assets/117227060/aa8931f6-a5b8-46e2-b028-8a515f0371dd)

**Comment by danny6167** [comment]
301 means you're getting a redirect. Most likely your panel is setup with SSL and you've configured WHMCS to access it over plain text. You enable SSL / https:// by ticking the secure box shown at the bottom of your screenshot. Don't try to add the protocol into the address.
