### ISSUE TITLE
Custom Fields

### ISSUE THREAD

**Issue by death8biths** [TrixterTheTux/Pterodactyl-WHMCS#15]
So im trying to set up my whmcs to work for per slot sales and all stuff like that but i cannot figure out how to use them with the module. Im trying to setup the per slot slider, asking for what game type they want (this is minecraft btw).

**Comment by TrixterTheTux** [comment]
How to use the custom fields with the module can be found here: https://github.com/TrixterTheTux/Pterodactyl-WHMCS#overwriting-values-through-configurable-options

**Comment by predator95** [comment]
> So im trying to set up my whmcs to work for per slot sales and all stuff like that but i cannot figure out how to use them with the module. Im trying to setup the per slot slider, asking for what game type they want (this is minecraft btw).

Hi
You resolved this problem? I tried with documentation, but don't work.
