### ISSUE TITLE
Custom Port

### ISSUE THREAD

**Issue by antonand03** [TrixterTheTux/Pterodactyl-WHMCS#16]
Hey, I run the panel on port (8888) but I cant seem to get it to work with this module? I get error code 0

**Comment by antonand03** [comment]
Still getting "Invalid status_code received: 0. Possible solutions: Most likely hostname is configured wrong causing the request never get executed."

**Comment by TrixterTheTux** [comment]
Enable module debug log, and check where it requests.

**Comment by antonand03** [comment]
get - http://panel.waypointhosting.com:8888/api/application/nodes
--

**Comment by TrixterTheTux** [comment]
There should be a log entry with "CURL ERROR" and the actual error message.

**Comment by antonand03** [comment]
http://prntscr.com/ji6yr8

**Comment by TrixterTheTux** [comment]
Get the latest version of the module, try again.
