### ISSUE TITLE
Account Created

### ISSUE THREAD

**Issue by buracat** [TrixterTheTux/Pterodactyl-WHMCS#19]
"This password reset token is invalid."  

Anyone know why every password reset token is instantly invalid?

**Comment by TrixterTheTux** [comment]
The module doesn't handle the password resetting or anything user related other than telling the API to create it if needed.

**Comment by buracat** [comment]
But normally no problem. There is a problem with the accounts created from the module

**Comment by TrixterTheTux** [comment]
The module doesn't create accounts in any way different from as it would have been through the panel itself. I have no control over password reset tokens.
