### ISSUE TITLE
Auto Setup

### ISSUE THREAD

**Issue by Atmazphere** [TrixterTheTux/Pterodactyl-WHMCS#20]
Whenever I use this, the addon will not create the server automatically. It sets the order as pending and has to manually approve it then from there it will setup the server. It is set to setup as soon as the order is placed, but sadly - it doesn’t.

**Comment by TrixterTheTux** [comment]
Not an issue with this module. This isn't something that should be handled by me in the first place, and you've not configured your instance of WHMCS properly.

**Comment by Atmazphere** [comment]
Not sure how this isn't related to your addon?

![screenshot_145](https://user-images.githubusercontent.com/16233421/44442108-994e4d80-a5a6-11e8-9bf9-fc20c5d7966e.png)

`Array
(
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => HttpException
                    [status] => 401
                    [detail] => An error was encountered while processing this request.
                )

        )

    [status_code] => 401
)
`

**Comment by TrixterTheTux** [comment]
I can't read your mind to know that there are errors, and you've just proven that the auto setup does run (but fail). 

I'll need the following:
- Panel Version
- Screenshot of the configured Pterodactyl server (where you enter the API key) 
- Screenshot of permissions assigned to the API key

**Comment by Atmazphere** [comment]
0.7.9 (Latest)
![unknown 1](https://user-images.githubusercontent.com/16233421/44474096-342b4400-a608-11e8-8b59-11fa6052c47b.png)
![unknown](https://user-images.githubusercontent.com/16233421/44474097-34c3da80-a608-11e8-939b-e64067c33085.png)
