### ISSUE TITLE
FAILED: Invalid status_code

### ISSUE THREAD

**Issue by Sceptox** [TrixterTheTux/Pterodactyl-WHMCS#21]
Hello!

I am getting this error when I am trying to "test connection".
Someone knows a fix for this specific problem?

`FAILED: Invalid status_code received: 0. Possible solutions: Most likely hostname is configured wrong causing the request never get executed.`

Module log:

```
Array
(
    [status_code] => 0
)

```

**Comment by TrixterTheTux** [comment]
Hi,

If possible, please use the [Pterodactyl Discord](https://pterodactyl.io/discord) for configuration issues (#whmcs channel)
