### ISSUE TITLE
Failed to get egg data

### ISSUE THREAD

**Issue by TunetexBG** [TrixterTheTux/Pterodactyl-WHMCS#26]
Failed to get egg data, received error code: 404. Enable module debug log for more info.

**Comment by TunetexBG** [comment]
http://prntscr.com/lbd8nd

**Comment by TrixterTheTux** [comment]
Hi,

You don't have nest id and/or egg id configured for the product. And please use GitHub issues for actual bugs. You can get configuring support in the [Pterodactyl Discord](https://discord.gg/pterodactyl).
