### ISSUE TITLE
Order Accept Encountered Problems Couldn't find any nodes satisfying the request.

### ISSUE THREAD

**Issue by tehcnoblade** [TrixterTheTux/Pterodactyl-WHMCS#31]
Order Accept Encountered Problems
Couldn't find any nodes satisfying the request.

How can I fix this? ty in advance :)

**Comment by TrixterTheTux** [comment]
Hi,

If possible, please use the [Pterodactyl Discord](https://pterodactyl.io/discord) for configuration issues (#whmcs channel)

**Comment by tehcnoblade** [comment]
If you're having this issue, make sure that you have allocated enough MBs in your Ptero Admin panel.
