### ISSUE TITLE
Curl timeout

### ISSUE THREAD

**Issue by RealRunSpace** [TrixterTheTux/Pterodactyl-WHMCS#33]
Hello, creating new servers lead to a "Operation timed out after 5001 milliseconds with 0 bytes received" timeout and the server starts being created. Because of this the user won't receive his username+password and will show as pending. Clicking on terminate button works correctly, is just when a server needs to be created. I have tried making the curl timeout to 10 and still getting this error. Thanks for the help.

**Comment by TrixterTheTux** [comment]
Hi,

If possible, please use the [Pterodactyl Discord](https://pterodactyl.io/discord) for configuration issues (#whmcs channel)

**Comment by RealRunSpace** [comment]
nobody seems to help :/
