### ISSUE TITLE
Not creating the server/user

### ISSUE THREAD

**Issue by disclearing** [TrixterTheTux/Pterodactyl-WHMCS#35]
Error: Failed to create user, received error code: 400. Enable module debug log for more info.

![13 33 57-16 03 19](https://user-images.githubusercontent.com/46827438/54476003-32b5a900-47f0-11e9-8362-9cefefb52ba4.png)

**Comment by TrixterTheTux** [comment]
Hi,

If possible, please use the [Pterodactyl Discord](https://pterodactyl.io/discord) for configuration issues (#whmcs channel)
