### ISSUE TITLE
Module Change Password not working

### ISSUE THREAD

**Issue by alexbgameson** [TrixterTheTux/Pterodactyl-WHMCS#37]
Hello.

When I attempt to change a users panel password through the WHMCS panel it says 
"Module Command Error
Not implemented, don't see need for this."

Can you help with this issue?

**Comment by danny6167** [comment]
WHMCS does not set pterodactyl user passwords. Use the pterodactyl admin panel to do this.

**Comment by alexbgameson** [comment]
But it does set the password on account creation so why cant it be updated using this method?

**Comment by TrixterTheTux** [comment]
It doesn't. None of the WHMCS's password actions work nor the password itself is valid.

**Comment by alexbgameson** [comment]
oh ok. How much $ for you to add this functionality?

**Comment by TrixterTheTux** [comment]
I'm not interested in making any of the password functionality work as you shouldn't be storing passwords in plaintext. It also has limitations which makes implementing it impossible anyway.

**Comment by korhox** [comment]
Is there any way to only set the password and not store it? Maybe just generate it, send it to pterodactyl and then set the password on whmcs to none? I belive many customers on WHMCS will be confused when they go to change password, fill in details and error "password change failed" appears.

And if this is not possible, can the change password-tab be hidden on on whmcs pages?
