### ISSUE TITLE
Add $param "Server Slots"

### ISSUE THREAD

**Issue by Stantastic** [TrixterTheTux/Pterodactyl-WHMCS#4]
Add the $param "Server Slots" to let customers pay by slots.

**Comment by LeCodeCo** [comment]
I'm against this as I feel like it's a bad selling practice which badly reflects Pterodactyl's performance to the public.

**Comment by Yomanz** [comment]
Maybe this could be expanded by allowing custom params to be made on whmcs?

**Comment by TrixterTheTux** [comment]
That is already possible on WHMCS, but unrelated to this as he wants overwriting of environment variables.

**Comment by TrixterTheTux** [comment]
Added the ability for overwriting variables + env variables in https://github.com/TrixterTheTux/Pterodactyl-WHMCS/commit/34d7bb8b80eaeb50ae696bbf8f2485e5a1740351
Check readme on how to use the WHMCS's provided configuration options with the module.
