### ISSUE TITLE
Add "default" or "minimum" disk space setting.

### ISSUE THREAD

**Issue by Stantastic** [TrixterTheTux/Pterodactyl-WHMCS#5]
In Products/Services-> Module Settings, add the option "default" or "minimum" disk space.

Why?

Allowing customers to order additional disk space if needed e.g. Product has 10GB disk space by default, the customer selects additional 3GB disk space, upon submiting the data to Pterodactyl "default" or "minimum" gets added to the customers selected additional disk space.

**Comment by TrixterTheTux** [comment]
Added the ability for overwriting variables + env variables in https://github.com/TrixterTheTux/Pterodactyl-WHMCS/commit/34d7bb8b80eaeb50ae696bbf8f2485e5a1740351
Check readme on how to use the WHMCS's provided configuration options with the module.
