### ISSUE TITLE
ClientArea>Manage Product Pterodactyl link and credentials

### ISSUE THREAD

**Issue by Stantastic** [TrixterTheTux/Pterodactyl-WHMCS#7]
Adding login credentials a link to the panel install and eventually some basic controls as in start/stop/restart would be helpfull

**Comment by TrixterTheTux** [comment]
There is already Go To Service button allowing you to go to the service on Pterodactyl's side and manage it.

**Comment by Stantastic** [comment]
But there's none for the clientarea

**Comment by TrixterTheTux** [comment]
Added in https://github.com/TrixterTheTux/Pterodactyl-WHMCS/commit/34d7bb8b80eaeb50ae696bbf8f2485e5a1740351
